name: GitHub to BitBucket

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 3"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login Source GitHub
        run: |
          gh --version
          echo "${{ secrets.SOURCE_TOKEN }}" | gh auth login --with-token
          gh auth status

      - name: List repos
        id: list_repos
        run: |
          repo_list=$(gh repo list k8scat -L 1000 --json name -t '{{range $i, $n := .}}{{if (gt $i 0)}},{{end}}{{$n.name}}{{end}}')
          echo "::set-output name=repo_list::${repo_list}"

      - name: Mirror Git
        uses: k8scat/action-mirror-git@v0.0.28
        with:
          source_protocol: https
          source_host: github.com
          source_username: k8scat
          source_token: ${{ secrets.SOURCE_TOKEN }}
          dest_protocol: https
          dest_host: bitbucket.org
          dest_username: k8scat
          dest_token: ${{ secrets.DEST_TOKEN_BITBUCKET }}
          push_tags: "true"
          mirror_repos: ${{ steps.list_repos.outputs.repo_list }}
          dest_create_repo_script: |
            curl \
              -u "${INPUT_DEST_USERNAME}:${INPUT_DEST_TOKEN}" \
              -H 'Content-Type: application/json' \
              -d '{"scm":"git"}' \
              "https://api.bitbucket.org/2.0/repositories/${INPUT_DEST_USERNAME}/${REPO_NAME}"
          force_push: "true"
          dest_delete_repo_script: |
            curl \
              -X DELETE \
              -u "${INPUT_DEST_USERNAME}:${INPUT_DEST_TOKEN}" \
              "https://api.bitbucket.org/2.0/repositories/${INPUT_DEST_USERNAME}/${REPO_NAME}"
          lark_webhook: ${{ secrets.LARK_WEBHOOK }}
          notify_prefix: "GitHub to BitBucket"
          ignore_error: "true"
